feat: реализованы модели данных, контроллеры, репозитори, CRUD для Bo…
VPerevozchikov/java-shareit pull request #2
Opened 2023-05-14 06:00 UTC by VPerevozchikov

…oking, Comments

2023-05-14 13:42 UTC, db-exp requested changes

2023-05-14 13:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    ItemRepository itemRepository;
репозиториев не должно быть на уровне контроллеров - это перемешивает слои.
К данным ходим только через сервисы

2023-05-14 13:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapperImpl.java
> +        bookingDto.setItem(itemMapper.toItem(itemRepository.findById(booking.getItemId())));
лучше вызвать ItemMapper, передав ему itemId и он уже сам сходит за данными через сервис

2023-05-14 13:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/repositories/BookingRepository.java
> +public interface BookingRepository extends JpaRepository<Booking, Long> {
не хватает аннотации Repository

2023-05-14 13:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    ItemRepository itemRepository;
лучше ходить в "чужие" сервис, а не "чужие" репозитории

2023-05-14 13:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        return new ResponseEntity<>(bookingDto, HttpStatus.CREATED);
давай переделаем - сервис возвращает данные, а не объект слоя "контроллер"

2023-05-14 13:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        return new ResponseEntity<>(bookingDto, HttpStatus.OK);
давай переделаем - сервис возвращает данные, а не объект слоя "контроллер"

2023-05-14 13:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        return new ResponseEntity<>(bookingDto, HttpStatus.OK);
давай переделаем - сервис возвращает данные, а не объект слоя "контроллер"

2023-05-14 13:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        return new ResponseEntity<>(bookingsDto, HttpStatus.OK);
давай переделаем - сервис возвращает данные, а не объект слоя "контроллер"

2023-05-14 13:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        return new ResponseEntity<>(bookingsDto, HttpStatus.OK);
давай переделаем - сервис возвращает данные, а не объект слоя "контроллер"

2023-05-14 13:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/dto/CommentCreationDto.java
> +public class CommentCreationDto {
предлагаю начать использовать аннотации валидации и Valid в контроллере

2023-05-14 13:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +                                           @RequestBody ItemCreationDto itemCreationDto) throws ValidationException {
нужна еще аннотация Valid, чтобы валидация начала работать

2023-05-14 13:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/mapper/CommentMapperImpl.java
> +public class CommentMapperImpl implements CommentMapper {
не обязательно делать компонентом, можно классом со статическими методами без имплиментации интерфейса

2023-05-14 13:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/repositories/ItemRepository.java
> +public interface ItemRepository extends JpaRepository<Item, Long> {
не хватает аннотации Repository

2023-05-14 13:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/repositories/CommentRepository.java
> +public interface CommentRepository extends JpaRepository<Comment, Long> {
не хватает аннотации Repository

2023-05-14 13:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    UserRepository userRepository;
нужно убрать из контроллера репозиторий

2023-05-14 13:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/repositories/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
не хватает аннотации Repository

2023-05-14 13:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +    public ResponseEntity<UserDto> addUser(UserCreationDto userCreationDto) throws ValidationException {
тут нужно вернуть просто Dto

2023-05-14 13:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +    public ResponseEntity<List<UserDto>> getUsers() {
тут нужно вернуть просто список Dto

2023-05-14 13:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +    public ResponseEntity<UserDto> updateUser(Long id, UserCreationDto userCreationDto) throws ValidationException {
тут нужно вернуть просто Dto

2023-05-14 13:42 UTC, db-exp commented on src/main/resources/schema.sql
> +    email varchar(512) NOT NULL,
очень много - 100 достаточно

2023-05-16 02:36 UTC, VPerevozchikov commented on src/main/resources/schema.sql
> +    email varchar(512) NOT NULL,
исправлено

2023-05-16 03:06 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +    public ResponseEntity<UserDto> updateUser(Long id, UserCreationDto userCreationDto) throws ValidationException {
исправлено

2023-05-16 03:06 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +    public ResponseEntity<List<UserDto>> getUsers() {
исправлено

2023-05-16 03:06 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +    public ResponseEntity<UserDto> addUser(UserCreationDto userCreationDto) throws ValidationException {
исправлено

2023-05-16 03:07 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        return new ResponseEntity<>(bookingDto, HttpStatus.CREATED);
исправлено

2023-05-16 03:07 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        return new ResponseEntity<>(bookingDto, HttpStatus.OK);
исправлено

2023-05-16 03:07 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        return new ResponseEntity<>(bookingDto, HttpStatus.OK);
исправлено

2023-05-16 03:07 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        return new ResponseEntity<>(bookingsDto, HttpStatus.OK);
исправлено

2023-05-16 03:08 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        return new ResponseEntity<>(bookingsDto, HttpStatus.OK);
исправлено

2023-05-16 03:13 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/user/repositories/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
исправлено

2023-05-16 03:13 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/item/repositories/CommentRepository.java
> +public interface CommentRepository extends JpaRepository<Comment, Long> {
исправлено

2023-05-16 03:14 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/item/repositories/ItemRepository.java
> +public interface ItemRepository extends JpaRepository<Item, Long> {
исправлено

2023-05-16 03:14 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/booking/repositories/BookingRepository.java
> +public interface BookingRepository extends JpaRepository<Booking, Long> {
исправлено

2023-05-16 03:26 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    ItemRepository itemRepository;
исправлено

2023-05-16 03:27 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    UserRepository userRepository;
исправлено

2023-05-17 03:42 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapperImpl.java
> +        bookingDto.setItem(itemMapper.toItem(itemRepository.findById(booking.getItemId())));
При попытке реализовать получил циклическую ссылку. Т.к. чтобы ItemMapper сходил за данными через ItemService ему надо передать эту зависимость. В свою очередь, в логику работы ItemService включен ItemMapper.

Я исключил "пролезание слоя" ItemRepository в BookingMapper, передавая в возрающие BookingDto методы Item напрямую.

2023-05-18 20:06 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    ItemRepository itemRepository;
Удалось частично заменить обращения к сервисам вместо репозиториев. Сталкиваюсь с проблемой циклических ссылок, в частности ItemService имеет поле BookingService, соответсвенно в BookingService на данном этапе не понятно как обращаться к ItemService, возникает ошибка "циклическая ссылка".

2023-05-18 20:16 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +                                           @RequestBody ItemCreationDto itemCreationDto) throws ValidationException {
исправлено

2023-05-18 20:16 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/item/dto/CommentCreationDto.java
> +public class CommentCreationDto {
исправлено

2023-05-19 03:06 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/item/mapper/CommentMapperImpl.java
> +public class CommentMapperImpl implements CommentMapper {
исправлено

2023-05-20 04:28 UTC, db-exp approved these changes

2023-05-20 04:28 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public ResponseEntity<BookingDto> addBooking(@RequestHeader("X-Sharer-User-Id") long userId,
throws ValidationException лучше не надо в явном виде - ValidationException нужно унаследовать от RuntimeException

2023-05-20 04:28 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    ItemRepository itemRepository;
Обычно так происходит, когда несколько перемешана ответственность
Как можно решить (один из вариантов) - развязать ItemService от Booking и после получения списка айтемов уже через BookingService дозаполнять бронирования вещей. Потому что сервис бронирования должен об этом знать, а сервис вещей нет
Это просто ответ на вопрос, а не призыв к доделкам :)

2023-05-20 04:34 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public ResponseEntity<BookingDto> addBooking(@RequestHeader("X-Sharer-User-Id") long userId,
ок, в следующем спринте поправлю, спасибо :)

2023-05-20 04:34 UTC, merged