feat: реализованы запросы на вещи, добавлены тесты
VPerevozchikov/java-shareit pull request #3
Opened 2023-07-01 07:57 UTC by VPerevozchikov

2023-07-01 19:21 UTC, db-exp requested changes

2023-07-01 19:21 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +            throws RuntimeException {
Runtime exception можно, но не нужно указывать в throws

2023-07-01 19:21 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +            throws RuntimeException {
Runtime exception можно, но не нужно указывать в throws

2023-07-01 19:21 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
>                                                   @RequestBody BookingCreationDto bookingCreationDto)
предлагаю добавить Valid

2023-07-01 19:21 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/repositories/BookingRepository.java
> +//            "join items as i on bookings.item_id = i.id " +
лучше удалять ненужный код

2023-07-01 19:21 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                                                 Integer size) throws ValidationException,
давай уберем везде throws ValidationException, она должна наследоваться от RuntimeException и явно прописывать в throws не нужно

2023-07-01 19:21 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +            throws RuntimeException {
давай уберем throws

2023-07-01 19:21 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +                                           @Valid @RequestBody ItemCreationDto itemCreationDto) throws RuntimeException {
давай уберем throws

2023-07-01 19:21 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +            throws RuntimeException {
давай уберем throws

2023-07-01 19:21 UTC, db-exp commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +    ItemRequestService itemRequestService;
private final стоит добавить

2023-07-01 19:21 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
private final стоит добавить для BookingService

2023-07-01 19:21 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
private final стоит добавить для ItemService

2023-07-01 19:21 UTC, db-exp commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +            throws RuntimeException {
давай уберем throws

2023-07-01 19:21 UTC, db-exp commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +                                                         @RequestBody ItemRequestCreationDto itemRequestCreationDto)
предалагаю добавить Valid

2023-07-01 19:21 UTC, db-exp commented on src/main/java/ru/practicum/shareit/request/mapper/ItemRequestMapper.java
> +    ItemRequestDto toDto(Optional<ItemRequest> itemRequest, List<ItemDto> items);
давай оставим этот метод или тот, что выше. Лучше этот)

2023-07-01 19:21 UTC, db-exp commented on src/main/java/ru/practicum/shareit/request/mapper/ItemRequestMapperImpl.java
> +            throw new NotFoundException(String.format(
это лучше бросать не в маппере, а в сервисе/репозитории

2023-07-01 19:21 UTC, db-exp commented on src/main/java/ru/practicum/shareit/request/mapper/ItemRequestMapperImpl.java
> +            throw new NotFoundException(String.format(
и тут стоит перенести NotFound в сервис или репозиторий на твой выбор

2023-07-01 19:21 UTC, db-exp commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +    ItemRepository itemRepository;
private final тут и ниже

2023-07-01 19:21 UTC, db-exp commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +                                         ItemRequestCreationDto itemRequestCreationDto) throws ValidationException,
throws не нужен, когда у нас наследование кастомных ошибок от RuntimeException. А кастомные ошибки редко наследуются от Exception напрямую

2023-07-01 19:21 UTC, db-exp commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +    public void validateRequestOnGetRequestsByAnotherUsers(Long userId, Integer from, Integer size) throws ValidationException,
throws

2023-07-01 19:21 UTC, db-exp commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +    public void validateRequestOnGetRequestById(Long userId, Long itemRequestId) throws ValidationException,
throws

2023-07-01 19:21 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +            throws RuntimeException {
throws не нужен

2023-07-01 19:21 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
private final на поля добавь, пожалуйста

2023-07-01 19:21 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
для get методов есть смысл повесить аннотацию Transactional c readOnly=true

2023-07-01 19:21 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
>      public BookingDto getBookingById(Long userId, Long bookingId) throws NotFoundException {
для get методов есть смысл повесить аннотацию Transactional c readOnly=true

2023-07-01 19:21 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
для get методов есть смысл повесить аннотацию Transactional c readOnly=true

2023-07-01 19:21 UTC, db-exp commented on src/test/java/ru/practicum/shareit/request/RequestJpaRepositoryTest.java
> +    public User userOne;
а зачем в тесте public? ) все поля тестового класса доступны только внутри этого класса

2023-07-01 19:21 UTC, db-exp commented on src/test/java/ru/practicum/shareit/request/RequestServiceIntegrationTest.java
> +    public UserCreationDto userCreationDtoOne;
public

2023-07-01 19:21 UTC, db-exp commented on src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +    UserCreationDto userCreationDtoOne;
стоит сделать private

2023-07-01 19:21 UTC, db-exp commented on src/test/java/ru/practicum/shareit/user/UserJpaRepositoryTest.java
> +    public User userOne;
стоит сделать private

2023-07-01 19:21 UTC, db-exp commented on src/test/java/ru/practicum/shareit/user/UserServiceIntegrationTest.java
> +    public UserCreationDto userCreationDtoOne;
стоит сделать private

2023-07-03 02:44 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +            throws RuntimeException {
исправлено

2023-07-03 02:45 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +            throws RuntimeException {
исправлен

2023-07-03 02:46 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/booking/repositories/BookingRepository.java
> +//            "join items as i on bookings.item_id = i.id " +
принял

2023-07-03 02:53 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                                                 Integer size) throws ValidationException,
исправлено

2023-07-03 02:59 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +            throws RuntimeException {
исправлено

2023-07-03 03:00 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +                                           @Valid @RequestBody ItemCreationDto itemCreationDto) throws RuntimeException {
исправлено

2023-07-03 03:00 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +            throws RuntimeException {
исправлено

2023-07-03 03:00 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +            throws RuntimeException {
исправлено

2023-07-03 03:02 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +                                         ItemRequestCreationDto itemRequestCreationDto) throws ValidationException,
исправлено

2023-07-03 03:02 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +    public void validateRequestOnGetRequestsByAnotherUsers(Long userId, Integer from, Integer size) throws ValidationException,
исправлено

2023-07-03 03:02 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +    public void validateRequestOnGetRequestById(Long userId, Long itemRequestId) throws ValidationException,
исправлено

2023-07-03 03:02 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +            throws RuntimeException {
исправлено

2023-07-03 03:19 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +    ItemRequestService itemRequestService;
добавлен

2023-07-03 03:19 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
добавлен

2023-07-03 03:19 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
добавлен

2023-07-03 03:27 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +    ItemRepository itemRepository;
добавлено

2023-07-05 03:03 UTC, VPerevozchikov commented on src/test/java/ru/practicum/shareit/request/RequestJpaRepositoryTest.java
> +    public User userOne;
исправлено

2023-07-05 03:03 UTC, VPerevozchikov commented on src/test/java/ru/practicum/shareit/request/RequestServiceIntegrationTest.java
> +    public UserCreationDto userCreationDtoOne;
исправлено

2023-07-05 03:04 UTC, VPerevozchikov commented on src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +    UserCreationDto userCreationDtoOne;
исправлено

2023-07-05 03:04 UTC, VPerevozchikov commented on src/test/java/ru/practicum/shareit/user/UserJpaRepositoryTest.java
> +    public User userOne;
исправлено

2023-07-05 03:04 UTC, VPerevozchikov commented on src/test/java/ru/practicum/shareit/user/UserServiceIntegrationTest.java
> +    public UserCreationDto userCreationDtoOne;
исправлено

2023-07-05 03:12 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
исправлено

2023-07-05 03:12 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
исправлено

2023-07-05 03:13 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
>      public BookingDto getBookingById(Long userId, Long bookingId) throws NotFoundException {
исправлено

2023-07-05 03:19 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/request/mapper/ItemRequestMapper.java
> +    ItemRequestDto toDto(Optional<ItemRequest> itemRequest, List<ItemDto> items);
исправлено

2023-07-05 03:29 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
>                                                   @RequestBody BookingCreationDto bookingCreationDto)
исправлено

2023-07-05 03:32 UTC, VPerevozchikov commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +                                                         @RequestBody ItemRequestCreationDto itemRequestCreationDto)
добавлено

2023-07-07 09:28 UTC, db-exp approved these changes

2023-07-07 16:18 UTC, merged